FROM eclipse-temurin:23-jdk-alpine AS build
WORKDIR /app
COPY target/*.jar app.jar

FROM eclipse-temurin:23-jre-alpine
WORKDIR /app
COPY --from=build /app/app.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]